FROM bitnami/minideb:buster

RUN install_packages \
      libasound2 \
      libatk1.0-0 \
      libatk-bridge2.0-0 \
      libatspi2.0-0 \
      libavahi-client3 \
      libavahi-common3 \
      libcairo2 \
      libcups2 \
      libdrm2 \
      libfribidi0 \
      libgbm1 \
      libnspr4 \
      libnss3 \
      libpango-1.0-0 \
      libpixman-1-0 \
      libthai0 \
      libwayland-server0 \
      libxcb-render0 \
      libxcb-shm0 \
      libxcomposite1 \
      libxdamage1 \
      libxext6 \
      libxfixes3 \
      libxkbcommon0 \
      libxrandr2 \
      libdatrie1 \
      libxrender1

RUN mkdir -p /workspace/libs && \
    export LIBS="\
        libnss3 libnssutil3 libsmime3 libnspr4 libplc4 libplds4 \
        libatk-1.0 libatk-bridge-2.0 libcups libXcomposite libXdamage libXext libXfixes libXrandr \
        libgbm libxkbcommon libpango-1.0 libcairo libasound libatspi \
        libXrender libdrm libwayland-server libavahi-common libavahi-client \
        libthai libfribidi libpixman-1 libdatrie libxcb-shm libxcb-render" && \
    for lib in $LIBS; do \
        matches=$(ldconfig -p | grep "$lib" | awk '{print $NF}' | sort -u); \
        if [ -z "$matches" ]; then \
            echo "❌ Error: Could not find shared object for $lib" >> /workspace/libs/errors; \
        fi; \
        echo "$matches" | while read path; do \
            echo "✅ Copying $path"; \
            cp --parents -v "$path" /workspace/libs/; \
        done; \
    done
