# .github/workflows/publish_testpypi.yml
---
name: test-n-build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  super-test:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
        python_v: ['3.8', '3.9', '3.10', '']
        # chrome_v: ['-1']
    name: Build and Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install Dependencies
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: >
          sudo apt-get update &&
          sudo apt-get install xvfb
          libnss3 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1
          libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0
          libcairo2 libasound2
        timeout-minutes: 3
      # must actually checkout for version determination
      - run: git checkout ${{ github.ref_name }}
      - run: uv python install ${{ matrix.python_v }}
      - run: uv python pin ${{ matrix.python_v }}
        if: ${{ matrix.python_v != '' }}
      # don't modify sync file! messes up version!
      - run: uv sync --all-extras --frozen # does order matter?
      - run: uv build
      - name: Reinstall from wheel
        run: >
          uv pip install dist/choreographer-$(uv
          run --no-sync --with setuptools-git-versioning
          setuptools-git-versioning)-py3-none-any.whl
      - run: uv run --no-sync choreo_get_chrome -v #--i ${{ matrix.chrome_v }}
      - name: Diagnose
        run:  uv run --no-sync choreo_diagnose --no-run
      - name: Test
        if: ${{ ! runner.debug && matrix.os != 'ubuntu-latest' }}
        run: uv run --no-sync poe test
        timeout-minutes: 8

      - name: Test (Linux)
        if: ${{ ! runner.debug && matrix.os == 'ubuntu-latest' }}
        run: xvfb-run uv run --no-sync poe test
        timeout-minutes: 8

      - name: Test (Debug)
        if: ${{ runner.debug && matrix.os != 'ubuntu-latest' }}
        run: uv run --no-sync poe debug-test
        timeout-minutes: 20

      - name: Test (Debug, Linux)
        if: ${{ runner.debug && matrix.os == 'ubuntu-latest' }}
        run: xvfb-run uv run --no-sync poe debug-test
        timeout-minutes: 8

  testpypi-publish:
    name: Upload release to TestPyPI
    needs: super-test
    if: always() && !cancelled() && !failure()
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/choreographer
    # Signs this workflow so pypi trusts it
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: git checkout ${{ github.ref_name }}
      - run: uv sync --frozen --all-extras
      - run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/.
